```
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-svc
spec:
  selector:
    app: kafka
  ports:
  - name: http
    protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: wurstmeister/kafka
        name: kafka
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "10.68.191.37"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "10.68.170.73:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
      imagePullSecrets:
      - name: harbor
      nodeSelector:
        kubernetes.io/role: node
      restartPolicy: Always
```			