# mysql k8s单节点部署yaml

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
    release: mysql
  name: mysql-6b8bf79d57-db2td
spec:
  containers:
  - image: mysql:5.7.14
    imagePullPolicy: IfNotPresent
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "system"
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  imagePullSecrets:
  - name: harbor

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels: 
    name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: http
    nodePort: 33306
  selector:
    name: mysql
```