```
---
kind: Service
apiVersion: v1
metadata:
  name: zk-svc
spec:
  selector:
    app: zookeeper
  ports:
  - name: http
    protocol: TCP
    port: 2181
    targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper:3.5
        name: zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
      imagePullSecrets:
      - name: harbor
      nodeSelector:
        kubernetes.io/role: node
      restartPolicy: Always
```			