```
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: af
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis-failover
    component: redis
    creator: redisfailover
    redis: redisfailover
    redisfailover: redisfailover
    statefulset.kubernetes.io/pod-name: rfr-redisfailover-0
```